### ISSUE TITLE
Consider alternative ratios

### ISSUE THREAD

**Issue by berb** [vs-uulm/latexslides-uulm#21]
LaTeX beamer supports different output ratios such as 1610, 149, 54, 43 and 32 as class loading option.

A modern look using 16:10 or 16:9 would require modifications of the first slide and maybe other parts of the presentation.

**Comment by matou** [comment]
16:10 now looks OK in branch [ratio](https://github.com/vs-uulm/latexslides-uulm/tree/ratio)
